# Project configuration for SpaceX Falcon 9 First Stage Landing Success

project:
  name: "SpaceX_Falcon9_Landing_Success"
  seed: 42

data:
  raw_path: "data/SpaceX_Falcon9_data.csv"   # update if your CSV lives elsewhere
  target_column: "Class"                     # 1 = success, 0 = failure
  date_column: "Date"
  # columns to remove before modelling
  drop_columns: ["Unnamed: 0", "Outcome", "Serial", "LandingPad"]
  # feature groups
  categorical: ["LaunchSite", "Orbit"]
  numeric: ["FlightNumber", "PayloadMass", "Flights", "GridFins", "Reused", "Legs",
            "Block", "ReusedCount", "Longitude", "Latitude", "Year"]
  # imputations for numeric columns
  impute:
    strategy:
      PayloadMass: "median"

preprocessing:
  one_hot:
    drop_first: true                 # reduce multicollinearity for linear models
  scale:
    columns: ["PayloadMass"]         # columns to standardize
    scaler: "StandardScaler"         # sklearn.preprocessing.StandardScaler

split:
  test_size: 0.2
  shuffle: true
  stratify: "Class"

models:
  logistic_regression:
    enabled: true
    params:
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 42

  knn:
    enabled: true
    params:
      n_neighbors: 5
      weights: "uniform"
      metric: "minkowski"

  decision_tree:
    enabled: true
    params:
      random_state: 42
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1

  xgboost:
    enabled: true
    params:
      random_state: 42
      eval_metric: "logloss"
      n_estimators: 50
      max_depth: 3
      learning_rate: 0.1

evaluation:
  cross_validation:
    folds: 5
    scoring: "accuracy"
  metrics: ["accuracy", "precision", "recall", "f1", "roc_auc"]

output:
  models_dir: "artifacts/models"
  reports_dir: "artifacts/reports"
  figures_dir: "artifacts/figures"

logging:
  level: "INFO"

profiles:
  dev:
    split:
      test_size: 0.3
  prod:
    split:
      test_size: 0.2
